event-animation-duration: 10 #seconds

boss-bar-radius: 50.0
boss-bar-title: "Событие"
#https://helpch.at/docs/1.16.5/org/bukkit/boss/BarColor.html
boss-bar-color: "RED"

#https://helpch.at/docs/1.16.5/org/bukkit/Sound.html
vulcan-tick-sound: "BLOCK_ANVIL_FALL"
vulcan-tick-sound-volume: 80

#количесвтво рандомный предметов, выпадающих после заверщения ивента (после завершения анимации вулкана)
random-items-drop-count: 1

#количево очков, которое будет начислятся при полнятии слезы гаста
#payer-points-item-cost: 1

#количесво денег в золотых самородках, выпадающих при ивенте
#gold-drop-cost: 1.01

#радиус дропа денег и поинтов. считается на 3 блока выше, чем точка начала ивента
dropping-radius: 4.0

#пустота чтобы не проигрывать
#при неверном вводе звука - проигрыватьсч он не будет
#указывать верхним регистром с нижним подчерркиванием
payer-points-pickedup-sound: ENTITY_ENDER_PEARL_THROW
payer-points-pickedup-sound-volume: 100

#словарь шанса выпадения + ид предмета из ""
#суммарный шанс выпадения ВСЕХ предметов не должен превышать 100
